project_id: pistachio-mlops-sbx
artifact_registry: northamerica-northeast2-docker.pkg.dev/pistachio-mlops-sbx/pistachio-base
gcs_bucket: pistachio_pipeline_sbx_bucket
training_pipeline_name: pistachio_training_pipeline
base_image_name: pistachio_base:0.0.1
vertex_image_name: pistachio_gcp_aip:0.0.1
pipeline_registry: https://northamerica-northeast2-kfp.pkg.dev/pistachio-mlops-sbx/pistachio-pipeline
model_registry_name: pistachio_classifier
model_registry_location: northamerica-northeast2


