# placeholders for pipeline

project_id: THE_PROJECT_ID
artifact_registry: THE_ARTIFACT_REGISTRY
gcs_bucket: THE_STORAGE_BUCKET
pipeline_name: pistachio_pipeline
base_image_name: pistachio_base:0.01


