# placeholders for pipeline

project_id: THE_PROJECT_ID
artifact_registry: THE_ARTIFACT_REGISTRY
gcs_bucket: THE_STORAGE_BUCKET
pipeline_name: pistachio_pipeline
base_image_name: pistachio_base:0.01
vertex_image_name: pistachio_gcp_aip:0.01
model_registry_name: pistachio_classifier
model_registry_location: northamerica-northeast2



